name: Deploy to GitHub Pages (DISABLED)

on:
  # Disabled - using manual deployment instead
  workflow_dispatch: # Manual trigger only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed successfully"
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      
    - name: Check build output
      run: |
        echo "Checking build directory..."
        ls -la build/
        echo "Build directory contents:"
        find build/ -type f | head -20
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build 